spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  application:
    name: ems
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ems?useUnicode=true&characterEncoding=utf-8
    username: root
    password: oneAPTX4869piece
#server:
#  servlet:
#    context-path: /ems

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.example.entity
server:
  servlet:
    jsp:
      init-parameters:
        development: true # hot deployment
